### ISSUE TITLE
Write installer

### ISSUE THREAD

**Issue by MarvinKlein1508** [MarvinKlein1508/FormPortal#7]
We should create a basic installer which sets up a new database based on the selected database provider as well as LDAP configuration.

The installer should be cross platform as well. Maybe a console app?

- [x] Install database
- [x] Choose login settings
- [x] Create local admin account
- [x] Apply new appsettings.json logic
- [x] Implement installer in app bundle
